import type { Range } from "@/lib/mock-data";

export type Modifier = {
  id: string;
  label: string;
  delta: Range;
};

export type MacroRange = {
  protein: Range;
  carbs: Range;
  fat: Range;
};

export type CandidateMeal = {
  id: string;
  name: string;
  chineseName: string;
  confidence: "High" | "Medium" | "Low";
  baseRange: Range;
  macroRange: MacroRange;
  note: string;
  aliases: string[];
  defaultModifierIds: string[];
  modifiers: Modifier[];
};

export const candidateMeals: CandidateMeal[] = [
  {
    id: "chicken-rice",
    name: "Hainanese Chicken Rice",
    chineseName: "海南鸡饭",
    confidence: "High",
    baseRange: [520, 650],
    macroRange: {
      protein: [28, 36],
      carbs: [52, 68],
      fat: [12, 20],
    },
    note: "Classic hawker lunch. Portion, skin, and sauce drive most of the swing.",
    aliases: ["chicken rice", "hainan chicken rice", "roasted chicken rice"],
    defaultModifierIds: ["half-rice", "skin-removed"],
    modifiers: [
      { id: "half-rice", label: "Half rice", delta: [-110, -80] },
      { id: "skin-removed", label: "Skin removed", delta: [-55, -35] },
      { id: "steamed", label: "Steamed", delta: [-10, 10] },
      { id: "roasted", label: "Roasted", delta: [20, 40] },
      { id: "add-egg", label: "Add egg", delta: [60, 85] },
      { id: "extra-sauce", label: "Extra sauce", delta: [25, 45] },
    ],
  },
  {
    id: "fishball-noodle",
    name: "Fishball Noodles (Dry)",
    chineseName: "鱼圆面",
    confidence: "Medium",
    baseRange: [420, 530],
    macroRange: {
      protein: [20, 28],
      carbs: [55, 70],
      fat: [10, 16],
    },
    note: "Good everyday meal. Sauce choice and noodle size matter more than users expect.",
    aliases: ["fishball noodle", "mee pok", "mee kia", "fish ball noodle"],
    defaultModifierIds: ["less-sauce"],
    modifiers: [
      { id: "less-sauce", label: "Less sauce", delta: [-40, -20] },
      { id: "extra-noodle", label: "Extra noodle", delta: [85, 120] },
      { id: "add-fishcake", label: "Add fishcake", delta: [45, 65] },
      { id: "soup-version", label: "Soup version", delta: [-30, -15] },
      { id: "add-meatballs", label: "Add meatballs", delta: [70, 95] },
    ],
  },
  {
    id: "prawn-noodle",
    name: "Prawn Noodles / Prawn Mee",
    chineseName: "虾面",
    confidence: "Medium",
    baseRange: [430, 590],
    macroRange: {
      protein: [24, 36],
      carbs: [45, 62],
      fat: [14, 22],
    },
    note: "Broth, noodle portion, prawns, and pork ribs change the calorie story quickly. Great test case for seafood + extras.",
    aliases: [
      "prawn noodle",
      "prawn noodles",
      "prawn mee",
      "shrimp noodle",
      "hae mee",
      "虾面",
      "排骨虾面",
      "pork rib prawn noodle",
      "pork rib prawn mee",
      "prawn rib mee",
    ],
    defaultModifierIds: ["soup-prawn-mee"],
    modifiers: [
      { id: "soup-prawn-mee", label: "Soup", delta: [0, 0] },
      { id: "dry-prawn-mee", label: "Dry version", delta: [30, 60] },
      { id: "less-noodle-prawn-mee", label: "Less noodles", delta: [-95, -65] },
      { id: "extra-noodle-prawn-mee", label: "Extra noodles", delta: [90, 130] },
      { id: "extra-prawns-prawn-mee", label: "Extra prawns", delta: [45, 75] },
      { id: "add-ribs-prawn-mee", label: "Add pork ribs", delta: [110, 160] },
    ],
  },
  {
    id: "cai-png",
    name: "Cai Png / Economy Rice",
    chineseName: "杂菜饭",
    confidence: "Medium",
    baseRange: [470, 620],
    macroRange: {
      protein: [18, 32],
      carbs: [50, 72],
      fat: [14, 24],
    },
    note: "The best correction UX test case. Components matter more than the photo label.",
    aliases: ["cai png", "economic rice", "economy rice", "chap fan"],
    defaultModifierIds: ["two-veg-one-meat"],
    modifiers: [
      { id: "less-rice-cai-png", label: "Less rice", delta: [-90, -60] },
      { id: "two-veg-one-meat", label: "2 veg 1 meat", delta: [-50, -20] },
      { id: "three-veg-cai-png", label: "3 veg", delta: [-80, -45] },
      { id: "extra-meat", label: "Extra meat", delta: [90, 130] },
      { id: "curry-drizzle", label: "Curry drizzle", delta: [35, 60] },
      { id: "fried-item", label: "Fried item", delta: [70, 110] },
      { id: "brown-rice", label: "Brown rice swap", delta: [-20, -10] },
    ],
  },
  {
    id: "kopi-c-siew-dai",
    name: "Kopi C Siew Dai",
    chineseName: "咖啡 C 少糖",
    confidence: "High",
    baseRange: [70, 110],
    macroRange: {
      protein: [2, 4],
      carbs: [8, 16],
      fat: [2, 4],
    },
    note: "Drinks are small, fast wins that help users feel the budget add up honestly.",
    aliases: ["kopi c siew dai", "kopi c", "coffee less sugar"],
    defaultModifierIds: ["hot"],
    modifiers: [
      { id: "hot", label: "Hot", delta: [0, 0] },
      { id: "iced", label: "Iced", delta: [10, 20] },
      { id: "gao", label: "Gao", delta: [15, 25] },
      { id: "less-milk", label: "Less milk", delta: [-15, -10] },
      { id: "kosong", label: "Kosong", delta: [-25, -20] },
    ],
  },
  {
    id: "nasi-lemak",
    name: "Nasi Lemak",
    chineseName: "椰浆饭",
    confidence: "Medium",
    baseRange: [560, 720],
    macroRange: {
      protein: [16, 28],
      carbs: [52, 70],
      fat: [22, 32],
    },
    note: "Great test case for side-item correction. Rice is only part of the calorie story here.",
    aliases: ["nasi lemak", "coconut rice", "椰浆饭"],
    defaultModifierIds: [],
    modifiers: [
      { id: "half-rice-lemak", label: "Half rice", delta: [-120, -90] },
      { id: "add-wing-lemak", label: "Add chicken wing", delta: [180, 240] },
      { id: "extra-sambal-lemak", label: "Extra sambal", delta: [20, 40] },
      { id: "skip-peanuts-lemak", label: "Skip peanuts", delta: [-55, -35] },
      { id: "fried-fish-lemak", label: "Fried fish", delta: [120, 170] },
    ],
  },
  {
    id: "yong-tau-foo",
    name: "Yong Tau Foo",
    chineseName: "酿豆腐",
    confidence: "Medium",
    baseRange: [320, 460],
    macroRange: {
      protein: [22, 32],
      carbs: [24, 40],
      fat: [10, 18],
    },
    note: "Healthy-looking, but noodles, rice, and fried pieces change the estimate fast.",
    aliases: ["yong tau foo", "ytf", "酿豆腐"],
    defaultModifierIds: ["soup-ytf"],
    modifiers: [
      { id: "soup-ytf", label: "Soup", delta: [0, 0] },
      { id: "dry-ytf", label: "Dry with sauce", delta: [70, 110] },
      { id: "add-noodles-ytf", label: "Add noodles", delta: [140, 190] },
      { id: "add-rice-ytf", label: "Add rice", delta: [180, 240] },
      { id: "fried-pieces-ytf", label: "More fried pieces", delta: [80, 120] },
    ],
  },
  {
    id: "lei-cha",
    name: "Lei Cha / Thunder Tea Rice",
    chineseName: "擂茶",
    confidence: "Medium",
    baseRange: [460, 685],
    macroRange: {
      protein: [18, 32],
      carbs: [58, 88],
      fat: [14, 28],
    },
    note: "Vegetable-forward, but rice, peanuts, fried anchovies, and tea paste decide whether it stays light.",
    aliases: [
      "lei cha",
      "leicha",
      "thunder tea rice",
      "thunder tea",
      "擂茶",
      "客家擂茶",
    ],
    defaultModifierIds: ["regular-rice-lei-cha", "peanuts-lei-cha"],
    modifiers: [
      { id: "less-rice-lei-cha", label: "Less rice", delta: [-110, -70] },
      { id: "regular-rice-lei-cha", label: "Regular rice", delta: [0, 0] },
      { id: "extra-rice-lei-cha", label: "Extra rice", delta: [90, 140] },
      { id: "peanuts-lei-cha", label: "Peanuts", delta: [70, 120] },
      { id: "less-peanuts-lei-cha", label: "Less peanuts", delta: [-55, -30] },
      { id: "fried-anchovies-lei-cha", label: "Fried anchovies", delta: [45, 90] },
      { id: "extra-tofu-lei-cha", label: "Extra tofu", delta: [50, 90] },
    ],
  },
  {
    id: "laksa",
    name: "Laksa",
    chineseName: "叻沙",
    confidence: "Medium",
    baseRange: [500, 650],
    macroRange: {
      protein: [18, 28],
      carbs: [42, 58],
      fat: [18, 28],
    },
    note: "The broth matters. One quick gravy or topping correction changes the range meaningfully.",
    aliases: ["laksa", "katong laksa", "curry noodle", "叻沙"],
    defaultModifierIds: ["less-gravy-laksa"],
    modifiers: [
      { id: "less-gravy-laksa", label: "Less gravy", delta: [-45, -25] },
      { id: "extra-noodle-laksa", label: "Extra noodles", delta: [90, 130] },
      { id: "add-cockles-laksa", label: "Add cockles", delta: [35, 60] },
      { id: "extra-puff-laksa", label: "More tau pok", delta: [40, 65] },
      { id: "extra-gravy-laksa", label: "Extra gravy", delta: [50, 80] },
    ],
  },
  {
    id: "roti-prata",
    name: "Roti Prata",
    chineseName: "印度煎饼",
    confidence: "Medium",
    baseRange: [280, 380],
    macroRange: {
      protein: [6, 10],
      carbs: [32, 44],
      fat: [10, 16],
    },
    note: "Breakfast and supper staple. Piece count and add-ons are the whole game.",
    aliases: ["prata", "roti prata", "plain prata", "egg prata", "印度煎饼"],
    defaultModifierIds: ["plain-prata"],
    modifiers: [
      { id: "plain-prata", label: "Plain", delta: [0, 0] },
      { id: "egg-prata", label: "Egg prata", delta: [70, 95] },
      { id: "two-piece-prata", label: "2 pieces", delta: [130, 180] },
      { id: "curry-dip-prata", label: "Extra curry", delta: [35, 55] },
      { id: "cheese-prata", label: "Cheese", delta: [90, 130] },
    ],
  },
  {
    id: "sliced-fish-soup",
    name: "Sliced Fish Soup",
    chineseName: "鱼片汤",
    confidence: "Medium",
    baseRange: [250, 360],
    macroRange: {
      protein: [24, 34],
      carbs: [8, 18],
      fat: [5, 10],
    },
    note: "Usually lighter, but milk broth and carb add-ons push it up quickly.",
    aliases: ["sliced fish soup", "fish soup", "鱼片汤", "鱼汤"],
    defaultModifierIds: ["clear-broth-fish-soup"],
    modifiers: [
      { id: "clear-broth-fish-soup", label: "Clear broth", delta: [0, 0] },
      { id: "evap-milk-fish-soup", label: "Evaporated milk", delta: [45, 75] },
      { id: "add-rice-fish-soup", label: "Add rice", delta: [180, 240] },
      { id: "add-beehoon-fish-soup", label: "Add bee hoon", delta: [120, 170] },
      { id: "fried-fish-soup", label: "Fried fish version", delta: [80, 120] },
    ],
  },
  {
    id: "bubble-tea",
    name: "Bubble Milk Tea",
    chineseName: "珍珠奶茶",
    confidence: "High",
    baseRange: [170, 250],
    macroRange: {
      protein: [2, 5],
      carbs: [28, 42],
      fat: [4, 8],
    },
    note: "Drink logging should feel honest, not punitive. Sugar and pearls are the biggest levers.",
    aliases: ["bubble tea", "boba", "milk tea", "珍珠奶茶"],
    defaultModifierIds: ["quarter-sugar-bbt"],
    modifiers: [
      { id: "zero-sugar-bbt", label: "0% sugar", delta: [-55, -35] },
      { id: "quarter-sugar-bbt", label: "25% sugar", delta: [0, 0] },
      { id: "half-sugar-bbt", label: "50% sugar", delta: [45, 70] },
      { id: "pearls-bbt", label: "Pearls", delta: [90, 130] },
      { id: "milk-foam-bbt", label: "Milk foam", delta: [80, 120] },
    ],
  },
  {
    id: "bak-chor-mee",
    name: "Bak Chor Mee",
    chineseName: "肉脞面",
    confidence: "Medium",
    baseRange: [520, 700],
    macroRange: {
      protein: [22, 34],
      carbs: [58, 82],
      fat: [18, 32],
    },
    note: "Common Singapore noodle meal. Sauce, lard, noodle size, and add-ons decide whether it stays moderate.",
    aliases: ["bak chor mee", "minced meat noodles", "meat noodle", "肉脞面", "肉搓面"],
    defaultModifierIds: ["dry-bcm"],
    modifiers: [
      { id: "dry-bcm", label: "Dry", delta: [0, 0] },
      { id: "soup-bcm", label: "Soup", delta: [-35, -15] },
      { id: "less-sauce-bcm", label: "Less sauce", delta: [-45, -20] },
      { id: "no-lard-bcm", label: "No lard", delta: [-60, -35] },
      { id: "extra-noodle-bcm", label: "Extra noodles", delta: [90, 130] },
      { id: "add-fishball-bcm", label: "Add fishball", delta: [45, 70] },
    ],
  },
  {
    id: "kaya-toast-set",
    name: "Kaya Toast Set",
    chineseName: "咖椰吐司套餐",
    confidence: "Medium",
    baseRange: [380, 520],
    macroRange: {
      protein: [14, 24],
      carbs: [45, 68],
      fat: [14, 24],
    },
    note: "A reasonable breakfast if it stays planned, but kaya, butter, and sweet coffee can stack quickly.",
    aliases: ["kaya toast", "yakun", "toast set", "soft boiled eggs", "咖椰吐司"],
    defaultModifierIds: ["two-eggs-kaya"],
    modifiers: [
      { id: "two-eggs-kaya", label: "2 soft-boiled eggs", delta: [120, 160] },
      { id: "less-butter-kaya", label: "Less butter", delta: [-55, -30] },
      { id: "less-kaya", label: "Less kaya", delta: [-35, -20] },
      { id: "kopi-c-kaya", label: "Kopi C", delta: [45, 85] },
      { id: "kopi-kosong-kaya", label: "Kopi kosong", delta: [5, 20] },
    ],
  },
  {
    id: "mala-xiang-guo",
    name: "Mala Xiang Guo",
    chineseName: "麻辣香锅",
    confidence: "Low",
    baseRange: [650, 980],
    macroRange: {
      protein: [26, 46],
      carbs: [35, 70],
      fat: [36, 62],
    },
    note: "Highly variable. A planned less-oil bowl can work; sauce, peanuts, fried items, noodles, and late-night timing are the risk.",
    aliases: ["mala xiang guo", "mala", "麻辣香锅", "ma la xiang guo", "spicy hotpot"],
    defaultModifierIds: ["less-oil-mala", "more-veg-mala"],
    modifiers: [
      { id: "less-oil-mala", label: "Less oil", delta: [-160, -90] },
      { id: "less-salt-mala", label: "Less salt", delta: [0, 0] },
      { id: "no-noodles-mala", label: "No noodles", delta: [-160, -100] },
      { id: "more-veg-mala", label: "More vegetables", delta: [-70, -30] },
      { id: "seafood-mala", label: "Seafood protein", delta: [-40, 20] },
      { id: "peanuts-mala", label: "Peanuts", delta: [90, 150] },
    ],
  },
  {
    id: "tuna-mayo-toast",
    name: "Tuna Mayo Toast",
    chineseName: "金枪鱼吐司",
    confidence: "Medium",
    baseRange: [380, 560],
    macroRange: {
      protein: [18, 32],
      carbs: [36, 58],
      fat: [12, 28],
    },
    note: "Useful convenience food, but mayo and buttered toast keep it from being a default diet-safe meal.",
    aliases: ["tuna toast", "tuna mayo toast", "tuna sandwich", "tuna mayo sandwich", "金枪鱼吐司", "金枪鱼三明治"],
    defaultModifierIds: ["mayo-tuna-toast"],
    modifiers: [
      { id: "mayo-tuna-toast", label: "Mayo", delta: [80, 140] },
      { id: "light-mayo-tuna-toast", label: "Light mayo", delta: [-45, -20] },
      { id: "wholemeal-tuna-toast", label: "Wholemeal bread", delta: [-20, 0] },
      { id: "half-tuna-toast", label: "Half portion", delta: [-210, -150] },
      { id: "add-egg-tuna-toast", label: "Add egg", delta: [60, 85] },
    ],
  },
  {
    id: "tau-huay-soy-dessert",
    name: "Tau Huay / Soy Beancurd Dessert",
    chineseName: "豆花豆浆甜品",
    confidence: "Medium",
    baseRange: [180, 340],
    macroRange: {
      protein: [8, 18],
      carbs: [22, 48],
      fat: [4, 12],
    },
    note: "Often a better dessert fallback when unsweetened, but toppings and syrup can turn it into a full sweet snack.",
    aliases: ["tau huay", "dou hua", "beancurd", "soy beancurd", "soy milk", "grass jelly soy milk", "豆花", "豆浆", "烧仙草"],
    defaultModifierIds: ["unsweetened-tau-huay"],
    modifiers: [
      { id: "unsweetened-tau-huay", label: "Unsweetened", delta: [-90, -45] },
      { id: "less-sugar-tau-huay", label: "Less sugar", delta: [-55, -25] },
      { id: "ginkgo-tau-huay", label: "Ginkgo", delta: [35, 70] },
      { id: "grass-jelly-soy", label: "Grass jelly soy milk", delta: [40, 90] },
      { id: "pearls-soy", label: "Pearls", delta: [100, 230] },
    ],
  },
  {
    id: "pig-trotter-rice",
    name: "Pig Trotter Rice",
    chineseName: "猪脚饭",
    confidence: "Medium",
    baseRange: [720, 980],
    macroRange: {
      protein: [24, 40],
      carbs: [70, 100],
      fat: [30, 52],
    },
    note: "Sauce, fatty skin, and rice portion make this heavy. It is better as a planned lunch than an accidental add-on.",
    aliases: ["pig trotter rice", "braised pork rice", "pork trotter rice", "猪脚饭", "卤肉饭"],
    defaultModifierIds: [],
    modifiers: [
      { id: "half-rice-pig-trotter", label: "Half rice", delta: [-120, -80] },
      { id: "less-gravy-pig-trotter", label: "Less gravy", delta: [-45, -20] },
      { id: "leaner-pork-pig-trotter", label: "Leaner pieces", delta: [-120, -70] },
      { id: "extra-veg-pig-trotter", label: "Extra vegetables", delta: [20, 45] },
    ],
  }

];
