import type { Range } from "@/lib/mock-data";

export type Modifier = {
  id: string;
  label: string;
  delta: Range;
};

export type MacroRange = {
  protein: Range;
  carbs: Range;
  fat: Range;
};

export type CandidateMeal = {
  id: string;
  name: string;
  chineseName: string;
  confidence: "High" | "Medium" | "Low";
  baseRange: Range;
  macroRange: MacroRange;
  note: string;
  aliases: string[];
  defaultModifierIds: string[];
  modifiers: Modifier[];
};

export const candidateMeals: CandidateMeal[] = [
  {
    id: "chicken-rice",
    name: "Hainanese Chicken Rice",
    chineseName: "海南鸡饭",
    confidence: "High",
    baseRange: [520, 650],
    macroRange: {
      protein: [28, 36],
      carbs: [52, 68],
      fat: [12, 20],
    },
    note: "Classic hawker lunch. Portion, skin, and sauce drive most of the swing.",
    aliases: ["chicken rice", "hainan chicken rice", "roasted chicken rice"],
    defaultModifierIds: ["half-rice", "skin-removed"],
    modifiers: [
      { id: "half-rice", label: "Half rice", delta: [-110, -80] },
      { id: "skin-removed", label: "Skin removed", delta: [-55, -35] },
      { id: "steamed", label: "Steamed", delta: [-10, 10] },
      { id: "roasted", label: "Roasted", delta: [20, 40] },
      { id: "add-egg", label: "Add egg", delta: [60, 85] },
      { id: "extra-sauce", label: "Extra sauce", delta: [25, 45] },
    ],
  },
  {
    id: "fishball-noodle",
    name: "Fishball Noodles (Dry)",
    chineseName: "鱼圆面",
    confidence: "Medium",
    baseRange: [420, 530],
    macroRange: {
      protein: [20, 28],
      carbs: [55, 70],
      fat: [10, 16],
    },
    note: "Good everyday meal. Sauce choice and noodle size matter more than users expect.",
    aliases: ["fishball noodle", "mee pok", "mee kia", "fish ball noodle"],
    defaultModifierIds: ["less-sauce"],
    modifiers: [
      { id: "less-sauce", label: "Less sauce", delta: [-40, -20] },
      { id: "extra-noodle", label: "Extra noodle", delta: [85, 120] },
      { id: "add-fishcake", label: "Add fishcake", delta: [45, 65] },
      { id: "soup-version", label: "Soup version", delta: [-30, -15] },
      { id: "add-meatballs", label: "Add meatballs", delta: [70, 95] },
    ],
  },
  {
    id: "prawn-noodle",
    name: "Prawn Noodles / Prawn Mee",
    chineseName: "虾面",
    confidence: "Medium",
    baseRange: [430, 590],
    macroRange: {
      protein: [24, 36],
      carbs: [45, 62],
      fat: [14, 22],
    },
    note: "Broth, noodle portion, prawns, and pork ribs change the calorie story quickly. Great test case for seafood + extras.",
    aliases: [
      "prawn noodle",
      "prawn noodles",
      "prawn mee",
      "shrimp noodle",
      "hae mee",
      "虾面",
      "排骨虾面",
      "pork rib prawn noodle",
      "pork rib prawn mee",
      "prawn rib mee",
    ],
    defaultModifierIds: ["soup-prawn-mee"],
    modifiers: [
      { id: "soup-prawn-mee", label: "Soup", delta: [0, 0] },
      { id: "dry-prawn-mee", label: "Dry version", delta: [30, 60] },
      { id: "less-noodle-prawn-mee", label: "Less noodles", delta: [-95, -65] },
      { id: "extra-noodle-prawn-mee", label: "Extra noodles", delta: [90, 130] },
      { id: "extra-prawns-prawn-mee", label: "Extra prawns", delta: [45, 75] },
      { id: "add-ribs-prawn-mee", label: "Add pork ribs", delta: [110, 160] },
    ],
  },
  {
    id: "cai-png",
    name: "Cai Png / Economy Rice",
    chineseName: "杂菜饭",
    confidence: "Medium",
    baseRange: [470, 620],
    macroRange: {
      protein: [18, 32],
      carbs: [50, 72],
      fat: [14, 24],
    },
    note: "The best correction UX test case. Components matter more than the photo label.",
    aliases: ["cai png", "economic rice", "economy rice", "chap fan"],
    defaultModifierIds: ["two-veg-one-meat"],
    modifiers: [
      { id: "less-rice-cai-png", label: "Less rice", delta: [-90, -60] },
      { id: "two-veg-one-meat", label: "2 veg 1 meat", delta: [-50, -20] },
      { id: "three-veg-cai-png", label: "3 veg", delta: [-80, -45] },
      { id: "extra-meat", label: "Extra meat", delta: [90, 130] },
      { id: "curry-drizzle", label: "Curry drizzle", delta: [35, 60] },
      { id: "fried-item", label: "Fried item", delta: [70, 110] },
      { id: "brown-rice", label: "Brown rice swap", delta: [-20, -10] },
    ],
  },
  {
    id: "kopi-c-siew-dai",
    name: "Kopi C Siew Dai",
    chineseName: "咖啡 C 少糖",
    confidence: "High",
    baseRange: [70, 110],
    macroRange: {
      protein: [2, 4],
      carbs: [8, 16],
      fat: [2, 4],
    },
    note: "Drinks are small, fast wins that help users feel the budget add up honestly.",
    aliases: ["kopi c siew dai", "kopi c", "coffee less sugar"],
    defaultModifierIds: ["hot"],
    modifiers: [
      { id: "hot", label: "Hot", delta: [0, 0] },
      { id: "iced", label: "Iced", delta: [10, 20] },
      { id: "gao", label: "Gao", delta: [15, 25] },
      { id: "less-milk", label: "Less milk", delta: [-15, -10] },
      { id: "kosong", label: "Kosong", delta: [-25, -20] },
    ],
  },
  {
    id: "nasi-lemak",
    name: "Nasi Lemak",
    chineseName: "椰浆饭",
    confidence: "Medium",
    baseRange: [560, 720],
    macroRange: {
      protein: [16, 28],
      carbs: [52, 70],
      fat: [22, 32],
    },
    note: "Great test case for side-item correction. Rice is only part of the calorie story here.",
    aliases: ["nasi lemak", "coconut rice", "椰浆饭"],
    defaultModifierIds: [],
    modifiers: [
      { id: "half-rice-lemak", label: "Half rice", delta: [-120, -90] },
      { id: "add-wing-lemak", label: "Add chicken wing", delta: [180, 240] },
      { id: "extra-sambal-lemak", label: "Extra sambal", delta: [20, 40] },
      { id: "skip-peanuts-lemak", label: "Skip peanuts", delta: [-55, -35] },
      { id: "fried-fish-lemak", label: "Fried fish", delta: [120, 170] },
    ],
  },
  {
    id: "yong-tau-foo",
    name: "Yong Tau Foo",
    chineseName: "酿豆腐",
    confidence: "Medium",
    baseRange: [320, 460],
    macroRange: {
      protein: [22, 32],
      carbs: [24, 40],
      fat: [10, 18],
    },
    note: "Healthy-looking, but noodles, rice, and fried pieces change the estimate fast.",
    aliases: ["yong tau foo", "ytf", "酿豆腐"],
    defaultModifierIds: ["soup-ytf"],
    modifiers: [
      { id: "soup-ytf", label: "Soup", delta: [0, 0] },
      { id: "dry-ytf", label: "Dry with sauce", delta: [70, 110] },
      { id: "add-noodles-ytf", label: "Add noodles", delta: [140, 190] },
      { id: "add-rice-ytf", label: "Add rice", delta: [180, 240] },
      { id: "fried-pieces-ytf", label: "More fried pieces", delta: [80, 120] },
    ],
  },
  {
    id: "lei-cha",
    name: "Lei Cha / Thunder Tea Rice",
    chineseName: "擂茶",
    confidence: "Medium",
    baseRange: [460, 685],
    macroRange: {
      protein: [18, 32],
      carbs: [58, 88],
      fat: [14, 28],
    },
    note: "Vegetable-forward, but rice, peanuts, fried anchovies, and tea paste decide whether it stays light.",
    aliases: [
      "lei cha",
      "leicha",
      "thunder tea rice",
      "thunder tea",
      "擂茶",
      "客家擂茶",
    ],
    defaultModifierIds: ["regular-rice-lei-cha", "peanuts-lei-cha"],
    modifiers: [
      { id: "less-rice-lei-cha", label: "Less rice", delta: [-110, -70] },
      { id: "regular-rice-lei-cha", label: "Regular rice", delta: [0, 0] },
      { id: "extra-rice-lei-cha", label: "Extra rice", delta: [90, 140] },
      { id: "peanuts-lei-cha", label: "Peanuts", delta: [70, 120] },
      { id: "less-peanuts-lei-cha", label: "Less peanuts", delta: [-55, -30] },
      { id: "fried-anchovies-lei-cha", label: "Fried anchovies", delta: [45, 90] },
      { id: "extra-tofu-lei-cha", label: "Extra tofu", delta: [50, 90] },
    ],
  },
  {
    id: "laksa",
    name: "Laksa",
    chineseName: "叻沙",
    confidence: "Medium",
    baseRange: [500, 650],
    macroRange: {
      protein: [18, 28],
      carbs: [42, 58],
      fat: [18, 28],
    },
    note: "The broth matters. One quick gravy or topping correction changes the range meaningfully.",
    aliases: ["laksa", "katong laksa", "curry noodle", "叻沙"],
    defaultModifierIds: ["less-gravy-laksa"],
    modifiers: [
      { id: "less-gravy-laksa", label: "Less gravy", delta: [-45, -25] },
      { id: "extra-noodle-laksa", label: "Extra noodles", delta: [90, 130] },
      { id: "add-cockles-laksa", label: "Add cockles", delta: [35, 60] },
      { id: "extra-puff-laksa", label: "More tau pok", delta: [40, 65] },
      { id: "extra-gravy-laksa", label: "Extra gravy", delta: [50, 80] },
    ],
  },
  {
    id: "roti-prata",
    name: "Roti Prata",
    chineseName: "印度煎饼",
    confidence: "Medium",
    baseRange: [280, 380],
    macroRange: {
      protein: [6, 10],
      carbs: [32, 44],
      fat: [10, 16],
    },
    note: "Breakfast and supper staple. Piece count and add-ons are the whole game.",
    aliases: ["prata", "roti prata", "plain prata", "egg prata", "印度煎饼"],
    defaultModifierIds: ["plain-prata"],
    modifiers: [
      { id: "plain-prata", label: "Plain", delta: [0, 0] },
      { id: "egg-prata", label: "Egg prata", delta: [70, 95] },
      { id: "two-piece-prata", label: "2 pieces", delta: [130, 180] },
      { id: "curry-dip-prata", label: "Extra curry", delta: [35, 55] },
      { id: "cheese-prata", label: "Cheese", delta: [90, 130] },
    ],
  },
  {
    id: "sliced-fish-soup",
    name: "Sliced Fish Soup",
    chineseName: "鱼片汤",
    confidence: "Medium",
    baseRange: [250, 360],
    macroRange: {
      protein: [24, 34],
      carbs: [8, 18],
      fat: [5, 10],
    },
    note: "Usually lighter, but milk broth and carb add-ons push it up quickly.",
    aliases: ["sliced fish soup", "fish soup", "鱼片汤", "鱼汤"],
    defaultModifierIds: ["clear-broth-fish-soup"],
    modifiers: [
      { id: "clear-broth-fish-soup", label: "Clear broth", delta: [0, 0] },
      { id: "evap-milk-fish-soup", label: "Evaporated milk", delta: [45, 75] },
      { id: "add-rice-fish-soup", label: "Add rice", delta: [180, 240] },
      { id: "add-beehoon-fish-soup", label: "Add bee hoon", delta: [120, 170] },
      { id: "fried-fish-soup", label: "Fried fish version", delta: [80, 120] },
    ],
  },
  {
    id: "bubble-tea",
    name: "Bubble Milk Tea",
    chineseName: "珍珠奶茶",
    confidence: "High",
    baseRange: [170, 250],
    macroRange: {
      protein: [2, 5],
      carbs: [28, 42],
      fat: [4, 8],
    },
    note: "Drink logging should feel honest, not punitive. Sugar and pearls are the biggest levers.",
    aliases: ["bubble tea", "boba", "milk tea", "珍珠奶茶"],
    defaultModifierIds: ["quarter-sugar-bbt"],
    modifiers: [
      { id: "zero-sugar-bbt", label: "0% sugar", delta: [-55, -35] },
      { id: "quarter-sugar-bbt", label: "25% sugar", delta: [0, 0] },
      { id: "half-sugar-bbt", label: "50% sugar", delta: [45, 70] },
      { id: "pearls-bbt", label: "Pearls", delta: [90, 130] },
      { id: "milk-foam-bbt", label: "Milk foam", delta: [80, 120] },
    ],
  },
  {
    id: "bak-chor-mee",
    name: "Bak Chor Mee",
    chineseName: "肉脞面",
    confidence: "Medium",
    baseRange: [520, 700],
    macroRange: {
      protein: [22, 34],
      carbs: [58, 82],
      fat: [18, 32],
    },
    note: "Common Singapore noodle meal. Sauce, lard, noodle size, and add-ons decide whether it stays moderate.",
    aliases: ["bak chor mee", "minced meat noodles", "meat noodle", "肉脞面", "肉搓面"],
    defaultModifierIds: ["dry-bcm"],
    modifiers: [
      { id: "dry-bcm", label: "Dry", delta: [0, 0] },
      { id: "soup-bcm", label: "Soup", delta: [-35, -15] },
      { id: "less-sauce-bcm", label: "Less sauce", delta: [-45, -20] },
      { id: "no-lard-bcm", label: "No lard", delta: [-60, -35] },
      { id: "extra-noodle-bcm", label: "Extra noodles", delta: [90, 130] },
      { id: "add-fishball-bcm", label: "Add fishball", delta: [45, 70] },
    ],
  },
  {
    id: "kaya-toast-set",
    name: "Kaya Toast Set",
    chineseName: "咖椰吐司套餐",
    confidence: "Medium",
    baseRange: [380, 520],
    macroRange: {
      protein: [14, 24],
      carbs: [45, 68],
      fat: [14, 24],
    },
    note: "A reasonable breakfast if it stays planned, but kaya, butter, and sweet coffee can stack quickly.",
    aliases: ["kaya toast", "yakun", "toast set", "soft boiled eggs", "咖椰吐司"],
    defaultModifierIds: ["two-eggs-kaya"],
    modifiers: [
      { id: "two-eggs-kaya", label: "2 soft-boiled eggs", delta: [120, 160] },
      { id: "less-butter-kaya", label: "Less butter", delta: [-55, -30] },
      { id: "less-kaya", label: "Less kaya", delta: [-35, -20] },
      { id: "kopi-c-kaya", label: "Kopi C", delta: [45, 85] },
      { id: "kopi-kosong-kaya", label: "Kopi kosong", delta: [5, 20] },
    ],
  },
  {
    id: "mala-xiang-guo",
    name: "Mala Xiang Guo",
    chineseName: "麻辣香锅",
    confidence: "Low",
    baseRange: [650, 980],
    macroRange: {
      protein: [26, 46],
      carbs: [35, 70],
      fat: [36, 62],
    },
    note: "Highly variable. A planned less-oil bowl can work; sauce, peanuts, fried items, noodles, and late-night timing are the risk.",
    aliases: ["mala xiang guo", "mala", "麻辣香锅", "ma la xiang guo", "spicy hotpot"],
    defaultModifierIds: ["less-oil-mala", "more-veg-mala"],
    modifiers: [
      { id: "less-oil-mala", label: "Less oil", delta: [-160, -90] },
      { id: "less-salt-mala", label: "Less salt", delta: [0, 0] },
      { id: "no-noodles-mala", label: "No noodles", delta: [-160, -100] },
      { id: "more-veg-mala", label: "More vegetables", delta: [-70, -30] },
      { id: "seafood-mala", label: "Seafood protein", delta: [-40, 20] },
      { id: "peanuts-mala", label: "Peanuts", delta: [90, 150] },
    ],
  },
  {
    id: "tuna-mayo-toast",
    name: "Tuna Mayo Toast",
    chineseName: "金枪鱼吐司",
    confidence: "Medium",
    baseRange: [380, 560],
    macroRange: {
      protein: [18, 32],
      carbs: [36, 58],
      fat: [12, 28],
    },
    note: "Useful convenience food, but mayo and buttered toast keep it from being a default diet-safe meal.",
    aliases: ["tuna toast", "tuna mayo toast", "tuna sandwich", "tuna mayo sandwich", "金枪鱼吐司", "金枪鱼三明治"],
    defaultModifierIds: ["mayo-tuna-toast"],
    modifiers: [
      { id: "mayo-tuna-toast", label: "Mayo", delta: [80, 140] },
      { id: "light-mayo-tuna-toast", label: "Light mayo", delta: [-45, -20] },
      { id: "wholemeal-tuna-toast", label: "Wholemeal bread", delta: [-20, 0] },
      { id: "half-tuna-toast", label: "Half portion", delta: [-210, -150] },
      { id: "add-egg-tuna-toast", label: "Add egg", delta: [60, 85] },
    ],
  },
  {
    id: "tau-huay-soy-dessert",
    name: "Tau Huay / Soy Beancurd Dessert",
    chineseName: "豆花豆浆甜品",
    confidence: "Medium",
    baseRange: [180, 340],
    macroRange: {
      protein: [8, 18],
      carbs: [22, 48],
      fat: [4, 12],
    },
    note: "Often a better dessert fallback when unsweetened, but toppings and syrup can turn it into a full sweet snack.",
    aliases: ["tau huay", "dou hua", "beancurd", "soy beancurd", "soy milk", "grass jelly soy milk", "豆花", "豆浆", "烧仙草"],
    defaultModifierIds: ["unsweetened-tau-huay"],
    modifiers: [
      { id: "unsweetened-tau-huay", label: "Unsweetened", delta: [-90, -45] },
      { id: "less-sugar-tau-huay", label: "Less sugar", delta: [-55, -25] },
      { id: "ginkgo-tau-huay", label: "Ginkgo", delta: [35, 70] },
      { id: "grass-jelly-soy", label: "Grass jelly soy milk", delta: [40, 90] },
      { id: "pearls-soy", label: "Pearls", delta: [100, 230] },
    ],
  },
  {
    id: "pig-trotter-rice",
    name: "Pig Trotter Rice",
    chineseName: "猪脚饭",
    confidence: "Medium",
    baseRange: [720, 980],
    macroRange: {
      protein: [24, 40],
      carbs: [70, 100],
      fat: [30, 52],
    },
    note: "Sauce, fatty skin, and rice portion make this heavy. It is better as a planned lunch than an accidental add-on.",
    aliases: ["pig trotter rice", "braised pork rice", "pork trotter rice", "猪脚饭", "卤肉饭"],
    defaultModifierIds: [],
    modifiers: [
      { id: "half-rice-pig-trotter", label: "Half rice", delta: [-120, -80] },
      { id: "less-gravy-pig-trotter", label: "Less gravy", delta: [-45, -20] },
      { id: "leaner-pork-pig-trotter", label: "Leaner pieces", delta: [-120, -70] },
      { id: "extra-veg-pig-trotter", label: "Extra vegetables", delta: [20, 45] },
    ],
  },
  {
    id: "chee-cheong-fun",
    name: "Chee Cheong Fun / Rice Rolls",
    chineseName: "肠粉",
    confidence: "Medium",
    baseRange: [260, 380],
    macroRange: {
      protein: [6, 16],
      carbs: [42, 62],
      fat: [5, 13],
    },
    note: "Steamed rice rolls are usually moderate, but sauce, oil, and seafood or char siew fillings change the range quickly.",
    aliases: ["chee cheong fun", "rice roll", "rice rolls", "scallop chee cheong fun", "prawn chee cheong fun", "char siew chee cheong fun", "肠粉", "扇贝肠粉", "虾肠粉", "叉烧肠粉"],
    defaultModifierIds: [],
    modifiers: [
      { id: "scallop-ccf", label: "Scallop filling", delta: [50, 90] },
      { id: "prawn-ccf", label: "Prawn filling", delta: [45, 80] },
      { id: "char-siew-ccf", label: "Char siew filling", delta: [70, 120] },
      { id: "extra-sauce-ccf", label: "Extra sauce", delta: [30, 65] },
      { id: "half-portion-ccf", label: "Half portion", delta: [-150, -100] },
    ],
  },
  {
    id: "lor-mai-gai",
    name: "Lor Mai Gai / Glutinous Rice Chicken",
    chineseName: "糯米鸡",
    confidence: "Medium",
    baseRange: [420, 560],
    macroRange: {
      protein: [16, 26],
      carbs: [58, 78],
      fat: [12, 22],
    },
    note: "Small-looking but dense. Glutinous rice, oil, and sauce make this a real breakfast item, not a light snack.",
    aliases: ["lor mai gai", "lo mai gai", "glutinous rice chicken", "steamed glutinous rice", "糯米鸡", "糯米飯"],
    defaultModifierIds: [],
    modifiers: [
      { id: "small-lor-mai-gai", label: "Small piece", delta: [-120, -70] },
      { id: "extra-chicken-lor-mai-gai", label: "More chicken", delta: [45, 85] },
      { id: "extra-sauce-lor-mai-gai", label: "Extra sauce", delta: [25, 55] },
      { id: "half-lor-mai-gai", label: "Half portion", delta: [-260, -190] },
    ],
  },
  {
    id: "steamed-pork-ribs",
    name: "Steamed Pork Ribs",
    chineseName: "蒸排骨",
    confidence: "Medium",
    baseRange: [220, 360],
    macroRange: {
      protein: [18, 30],
      carbs: [4, 12],
      fat: [14, 26],
    },
    note: "Dim sum pork ribs are protein-heavy, but fatty cuts, black bean sauce, and oil can push calories up.",
    aliases: ["steamed pork ribs", "pork ribs", "black bean ribs", "dim sum ribs", "蒸排骨", "豉汁蒸排骨", "排骨"],
    defaultModifierIds: [],
    modifiers: [
      { id: "black-bean-ribs", label: "Black bean sauce", delta: [20, 45] },
      { id: "fatty-ribs", label: "Fatty pieces", delta: [60, 120] },
      { id: "small-ribs", label: "Small plate", delta: [-80, -45] },
      { id: "shared-ribs", label: "Shared portion", delta: [-140, -90] },
    ],
  },
  {
    id: "cucumber-side",
    name: "Cucumber / Cucumber Side",
    chineseName: "黄瓜",
    confidence: "High",
    baseRange: [15, 40],
    macroRange: {
      protein: [0, 2],
      carbs: [3, 8],
      fat: [0, 1],
    },
    note: "Very light unless dressed with oil, sesame sauce, or sugar-heavy pickling liquid.",
    aliases: ["cucumber", "cucumber side", "sliced cucumber", "黄瓜", "青瓜", "拍黄瓜"],
    defaultModifierIds: [],
    modifiers: [
      { id: "chili-oil-cucumber", label: "Chili oil dressing", delta: [35, 90] },
      { id: "sesame-cucumber", label: "Sesame dressing", delta: [45, 110] },
      { id: "large-cucumber", label: "Large serving", delta: [20, 45] },
    ],
  },
  {
    id: "siew-mai",
    name: "Siew Mai",
    chineseName: "烧卖",
    confidence: "Medium",
    baseRange: [180, 280],
    macroRange: { protein: [12, 20], carbs: [12, 24], fat: [8, 16] },
    note: "Dim sum portion depends on piece count. Usually manageable, but easy to stack with other breakfast items.",
    aliases: ["siew mai", "siu mai", "shumai", "pork dumpling", "烧卖", "燒賣"],
    defaultModifierIds: ["three-siew-mai"],
    modifiers: [
      { id: "three-siew-mai", label: "3 pieces", delta: [0, 0] },
      { id: "four-siew-mai", label: "4 pieces", delta: [60, 95] },
      { id: "two-siew-mai", label: "2 pieces", delta: [-75, -45] },
    ],
  },
  {
    id: "har-gow",
    name: "Har Gow / Prawn Dumplings",
    chineseName: "虾饺",
    confidence: "Medium",
    baseRange: [160, 240],
    macroRange: { protein: [10, 18], carbs: [18, 30], fat: [3, 8] },
    note: "Usually lighter than fried dim sum, but piece count and dipping sauce still matter.",
    aliases: ["har gow", "har gao", "prawn dumpling", "shrimp dumpling", "虾饺", "蝦餃"],
    defaultModifierIds: ["three-har-gow"],
    modifiers: [
      { id: "three-har-gow", label: "3 pieces", delta: [0, 0] },
      { id: "four-har-gow", label: "4 pieces", delta: [50, 80] },
      { id: "two-har-gow", label: "2 pieces", delta: [-70, -45] },
    ],
  },
  {
    id: "carrot-cake",
    name: "Fried Carrot Cake / Chai Tow Kway",
    chineseName: "菜头粿",
    confidence: "Medium",
    baseRange: [420, 650],
    macroRange: { protein: [10, 20], carbs: [50, 82], fat: [18, 34] },
    note: "A hawker classic where oil and egg drive the swing. Black sauce adds sweetness but oil is usually the bigger lever.",
    aliases: ["fried carrot cake", "chai tow kway", "carrot cake", "white carrot cake", "black carrot cake", "菜头粿", "萝卜糕", "蘿蔔糕"],
    defaultModifierIds: [],
    modifiers: [
      { id: "white-carrot-cake", label: "White version", delta: [-25, 20] },
      { id: "black-carrot-cake", label: "Black sauce", delta: [35, 80] },
      { id: "less-oil-carrot-cake", label: "Less oil", delta: [-120, -65] },
      { id: "small-carrot-cake", label: "Small plate", delta: [-160, -95] },
    ],
  },
  {
    id: "char-kway-teow",
    name: "Char Kway Teow",
    chineseName: "炒粿条",
    confidence: "Medium",
    baseRange: [650, 900],
    macroRange: { protein: [18, 30], carbs: [70, 98], fat: [28, 48] },
    note: "High variance and usually oil-heavy. Cockles, Chinese sausage, lard, and portion size all matter.",
    aliases: ["char kway teow", "char kuay teow", "fried kway teow", "炒粿条", "炒果条", "炒粿條"],
    defaultModifierIds: [],
    modifiers: [
      { id: "less-oil-ckt", label: "Less oil", delta: [-160, -90] },
      { id: "small-ckt", label: "Small plate", delta: [-180, -120] },
      { id: "extra-cockles-ckt", label: "Extra cockles", delta: [35, 70] },
      { id: "no-lard-ckt", label: "No lard", delta: [-80, -45] },
    ],
  },
  {
    id: "hokkien-mee",
    name: "Hokkien Mee",
    chineseName: "福建面",
    confidence: "Medium",
    baseRange: [520, 720],
    macroRange: { protein: [20, 34], carbs: [62, 88], fat: [18, 32] },
    note: "Noodle portion, oil, pork lard, and seafood topping decide whether it stays moderate.",
    aliases: ["hokkien mee", "fried hokkien mee", "福建面", "福建炒虾面", "福建炒蝦麵"],
    defaultModifierIds: [],
    modifiers: [
      { id: "less-noodle-hokkien", label: "Less noodles", delta: [-120, -80] },
      { id: "extra-seafood-hokkien", label: "Extra seafood", delta: [45, 90] },
      { id: "no-lard-hokkien", label: "No lard", delta: [-70, -40] },
      { id: "small-hokkien", label: "Small plate", delta: [-160, -100] },
    ],
  },
  {
    id: "wanton-mee",
    name: "Wanton Mee",
    chineseName: "云吞面",
    confidence: "Medium",
    baseRange: [430, 620],
    macroRange: { protein: [18, 30], carbs: [58, 78], fat: [12, 24] },
    note: "Dry sauce and char siew portion are the main levers. Soup version is usually a little lighter.",
    aliases: ["wanton mee", "wantan mee", "wan tan mee", "wonton noodle", "云吞面", "雲吞麵"],
    defaultModifierIds: ["dry-wanton-mee"],
    modifiers: [
      { id: "dry-wanton-mee", label: "Dry", delta: [0, 0] },
      { id: "soup-wanton-mee", label: "Soup", delta: [-60, -25] },
      { id: "extra-char-siew-wanton", label: "Extra char siew", delta: [80, 140] },
      { id: "less-noodle-wanton", label: "Less noodles", delta: [-100, -70] },
    ],
  },
  {
    id: "ban-mian",
    name: "Ban Mian / Handmade Noodles",
    chineseName: "板面",
    confidence: "Medium",
    baseRange: [430, 620],
    macroRange: { protein: [20, 34], carbs: [58, 82], fat: [10, 22] },
    note: "A solid everyday meal, but dry chilli versions and extra noodles push it up.",
    aliases: ["ban mian", "you mian", "mee hoon kueh", "handmade noodles", "板面", "幼面", "面粉粿"],
    defaultModifierIds: ["soup-ban-mian"],
    modifiers: [
      { id: "soup-ban-mian", label: "Soup", delta: [0, 0] },
      { id: "dry-ban-mian", label: "Dry chilli", delta: [80, 140] },
      { id: "add-egg-ban-mian", label: "Add egg", delta: [60, 85] },
      { id: "less-noodle-ban-mian", label: "Less noodles", delta: [-110, -75] },
    ],
  },
  {
    id: "mee-siam",
    name: "Mee Siam",
    chineseName: "米暹",
    confidence: "Medium",
    baseRange: [420, 560],
    macroRange: { protein: [12, 22], carbs: [62, 86], fat: [10, 20] },
    note: "The gravy is not the only issue; noodle portion and egg decide the meal size.",
    aliases: ["mee siam", "米暹", "暹罗米粉"],
    defaultModifierIds: [],
    modifiers: [
      { id: "less-noodle-mee-siam", label: "Less noodles", delta: [-110, -70] },
      { id: "add-egg-mee-siam", label: "Add egg", delta: [60, 85] },
      { id: "extra-gravy-mee-siam", label: "Extra gravy", delta: [20, 45] },
    ],
  },
  {
    id: "mee-rebus",
    name: "Mee Rebus",
    chineseName: "马来卤面",
    confidence: "Medium",
    baseRange: [480, 650],
    macroRange: { protein: [14, 24], carbs: [68, 92], fat: [14, 26] },
    note: "Thick gravy, noodles, and fried garnish can make it heavier than it looks.",
    aliases: ["mee rebus", "马来卤面", "馬來滷麵"],
    defaultModifierIds: [],
    modifiers: [
      { id: "less-gravy-mee-rebus", label: "Less gravy", delta: [-50, -25] },
      { id: "less-noodle-mee-rebus", label: "Less noodles", delta: [-120, -80] },
      { id: "add-egg-mee-rebus", label: "Add egg", delta: [60, 85] },
    ],
  },
  {
    id: "nasi-padang",
    name: "Nasi Padang",
    chineseName: "巴东饭",
    confidence: "Low",
    baseRange: [650, 980],
    macroRange: { protein: [22, 42], carbs: [62, 98], fat: [28, 56] },
    note: "Treat as a component meal. Curry, coconut gravy, fried items, and rice portion decide the final range.",
    aliases: ["nasi padang", "padang rice", "巴东饭", "马来饭", "mutton curry rice", "rendang rice"],
    defaultModifierIds: [],
    modifiers: [
      { id: "half-rice-padang", label: "Half rice", delta: [-120, -80] },
      { id: "rendang-padang", label: "Rendang", delta: [120, 220] },
      { id: "fried-item-padang", label: "Fried item", delta: [140, 240] },
      { id: "less-gravy-padang", label: "Less gravy", delta: [-80, -40] },
    ],
  },
  {
    id: "satay",
    name: "Satay",
    chineseName: "沙爹",
    confidence: "Medium",
    baseRange: [300, 450],
    macroRange: { protein: [22, 36], carbs: [12, 28], fat: [16, 30] },
    note: "Skewer count and peanut sauce matter. Shared satay should usually be scaled down.",
    aliases: ["satay", "chicken satay", "beef satay", "mutton satay", "沙爹"],
    defaultModifierIds: ["five-satay"],
    modifiers: [
      { id: "five-satay", label: "5 skewers", delta: [0, 0] },
      { id: "ten-satay", label: "10 skewers", delta: [300, 450] },
      { id: "peanut-sauce-satay", label: "Peanut sauce", delta: [80, 160] },
      { id: "rice-cake-satay", label: "Rice cake", delta: [80, 140] },
    ],
  },
  {
    id: "popiah",
    name: "Popiah",
    chineseName: "薄饼",
    confidence: "Medium",
    baseRange: [180, 280],
    macroRange: { protein: [6, 12], carbs: [28, 42], fat: [5, 12] },
    note: "Often a reasonable snack, but sweet sauce, peanuts, and fried bits can add up.",
    aliases: ["popiah", "fresh spring roll", "薄饼", "薄餅"],
    defaultModifierIds: [],
    modifiers: [
      { id: "extra-peanuts-popiah", label: "Extra peanuts", delta: [45, 90] },
      { id: "extra-sauce-popiah", label: "Extra sweet sauce", delta: [25, 60] },
      { id: "two-popiah", label: "2 rolls", delta: [180, 280] },
    ],
  },
  {
    id: "oyster-omelette",
    name: "Oyster Omelette / Orh Luak",
    chineseName: "蚝煎",
    confidence: "Medium",
    baseRange: [550, 820],
    macroRange: { protein: [20, 34], carbs: [36, 62], fat: [34, 56] },
    note: "Oil and starch make this heavy quickly. Usually better treated as a shared dish.",
    aliases: ["oyster omelette", "orh luak", "or luak", "蚝煎", "蠔煎"],
    defaultModifierIds: [],
    modifiers: [
      { id: "shared-orh-luak", label: "Shared portion", delta: [-360, -240] },
      { id: "less-oil-orh-luak", label: "Less oil", delta: [-120, -70] },
      { id: "extra-oyster-orh-luak", label: "Extra oysters", delta: [45, 90] },
    ],
  },
  {
    id: "rojak",
    name: "Rojak",
    chineseName: "罗惹",
    confidence: "Medium",
    baseRange: [320, 520],
    macroRange: { protein: [8, 18], carbs: [46, 70], fat: [10, 24] },
    note: "Fruit and veg help, but sauce, peanuts, and you tiao decide the calorie story.",
    aliases: ["rojak", "indian rojak", "chinese rojak", "罗惹", "囉惹"],
    defaultModifierIds: [],
    modifiers: [
      { id: "less-sauce-rojak", label: "Less sauce", delta: [-70, -35] },
      { id: "extra-youtiao-rojak", label: "Extra you tiao", delta: [100, 180] },
      { id: "extra-peanut-rojak", label: "Extra peanuts", delta: [70, 130] },
      { id: "shared-rojak", label: "Shared portion", delta: [-180, -120] },
    ],
  },
  {
    id: "chwee-kueh",
    name: "Chwee Kueh",
    chineseName: "水粿",
    confidence: "Medium",
    baseRange: [260, 420],
    macroRange: { protein: [4, 9], carbs: [42, 66], fat: [8, 20] },
    note: "Rice cakes are light alone; preserved radish oil is the calorie lever.",
    aliases: ["chwee kueh", "shui kueh", "水粿", "水糕"],
    defaultModifierIds: ["four-chwee-kueh"],
    modifiers: [
      { id: "four-chwee-kueh", label: "4 pieces", delta: [0, 0] },
      { id: "six-chwee-kueh", label: "6 pieces", delta: [120, 190] },
      { id: "less-chai-poh", label: "Less chai poh oil", delta: [-80, -40] },
    ],
  },
  {
    id: "mee-goreng",
    name: "Mee Goreng",
    chineseName: "印度炒面",
    confidence: "Medium",
    baseRange: [600, 850],
    macroRange: { protein: [18, 32], carbs: [78, 108], fat: [22, 42] },
    note: "Usually carb-heavy and oil-forward. Egg, mutton, and portion size are the main corrections.",
    aliases: ["mee goreng", "indian mee goreng", "mamak mee goreng", "印度炒面", "炒面"],
    defaultModifierIds: [],
    modifiers: [
      { id: "small-mee-goreng", label: "Small plate", delta: [-180, -110] },
      { id: "add-egg-mee-goreng", label: "Add egg", delta: [60, 85] },
      { id: "mutton-mee-goreng", label: "Mutton", delta: [120, 220] },
      { id: "less-oil-mee-goreng", label: "Less oil", delta: [-120, -70] },
    ],
  },
  {
    id: "fried-rice",
    name: "Fried Rice",
    chineseName: "炒饭",
    confidence: "Medium",
    baseRange: [550, 780],
    macroRange: { protein: [16, 30], carbs: [72, 102], fat: [18, 34] },
    note: "The reliable fallback for mixed rice photos. Oil, egg, meat, and portion size drive the range.",
    aliases: ["fried rice", "egg fried rice", "yangzhou fried rice", "炒饭", "蛋炒饭", "扬州炒饭"],
    defaultModifierIds: [],
    modifiers: [
      { id: "small-fried-rice", label: "Small plate", delta: [-170, -100] },
      { id: "extra-egg-fried-rice", label: "Extra egg", delta: [60, 85] },
      { id: "seafood-fried-rice", label: "Seafood", delta: [50, 110] },
      { id: "less-oil-fried-rice", label: "Less oil", delta: [-110, -65] },
    ],
  },
  {
    id: "steamed-fish",
    name: "Steamed Fish",
    chineseName: "蒸鱼",
    confidence: "Medium",
    baseRange: [220, 380],
    macroRange: { protein: [28, 46], carbs: [2, 10], fat: [8, 20] },
    note: "Usually a strong shared-dinner protein if sauce and oil stay moderate.",
    aliases: ["steamed fish", "hong kong steamed fish", "soy sauce steamed fish", "蒸鱼", "清蒸鱼", "港蒸鱼"],
    defaultModifierIds: [],
    modifiers: [
      { id: "shared-steamed-fish", label: "Shared portion", delta: [-150, -90] },
      { id: "extra-oil-steamed-fish", label: "Extra oil", delta: [60, 130] },
      { id: "large-steamed-fish", label: "Large portion", delta: [120, 220] },
    ],
  },
  {
    id: "curry-fish-head",
    name: "Curry Fish Head",
    chineseName: "咖喱鱼头",
    confidence: "Low",
    baseRange: [680, 1100],
    macroRange: { protein: [35, 60], carbs: [18, 42], fat: [42, 78] },
    note: "Usually shared. Curry gravy and rice are the hidden budget drivers.",
    aliases: ["curry fish head", "fish head curry", "咖喱鱼头", "咖喱魚頭"],
    defaultModifierIds: ["shared-curry-fish-head"],
    modifiers: [
      { id: "shared-curry-fish-head", label: "Shared portion", delta: [-440, -280] },
      { id: "more-gravy-curry-fish", label: "More gravy", delta: [90, 180] },
      { id: "add-rice-curry-fish", label: "Add rice", delta: [180, 240] },
    ],
  },
  {
    id: "sweet-sour-pork",
    name: "Sweet and Sour Pork",
    chineseName: "咕噜肉",
    confidence: "Medium",
    baseRange: [420, 680],
    macroRange: { protein: [20, 34], carbs: [34, 58], fat: [20, 40] },
    note: "A shared zi char dish. Fried batter and sweet sauce are the big calorie sources.",
    aliases: ["sweet and sour pork", "sweet sour pork", "gu lou yuk", "咕噜肉", "古老肉"],
    defaultModifierIds: ["shared-sweet-sour-pork"],
    modifiers: [
      { id: "shared-sweet-sour-pork", label: "Shared portion", delta: [-230, -150] },
      { id: "large-sweet-sour-pork", label: "Large portion", delta: [160, 260] },
      { id: "extra-sauce-sweet-sour", label: "Extra sauce", delta: [45, 90] },
    ],
  },
  {
    id: "kangkong-belacan",
    name: "Kang Kong Belacan",
    chineseName: "马来风光",
    confidence: "Medium",
    baseRange: [180, 320],
    macroRange: { protein: [5, 12], carbs: [12, 24], fat: [10, 22] },
    note: "Vegetable dish, but oil and sambal mean it is not free. Usually shared.",
    aliases: ["kang kong belacan", "sambal kangkong", "kangkong", "马来风光", "参巴空心菜", "空心菜"],
    defaultModifierIds: ["shared-kangkong"],
    modifiers: [
      { id: "shared-kangkong", label: "Shared portion", delta: [-100, -60] },
      { id: "less-oil-kangkong", label: "Less oil", delta: [-60, -30] },
      { id: "large-kangkong", label: "Large plate", delta: [80, 140] },
    ],
  },
  {
    id: "kopi-o-kosong",
    name: "Kopi O Kosong",
    chineseName: "咖啡乌无糖",
    confidence: "High",
    baseRange: [5, 20],
    macroRange: { protein: [0, 1], carbs: [0, 2], fat: [0, 1] },
    note: "A very low-calorie drink if it is truly kosong.",
    aliases: ["kopi o kosong", "kopi kosong", "black coffee no sugar", "咖啡乌无糖", "咖啡乌 kosong"],
    defaultModifierIds: [],
    modifiers: [
      { id: "iced-kopi-o-kosong", label: "Iced", delta: [0, 10] },
      { id: "siew-dai-kopi-o", label: "Siew dai", delta: [35, 70] },
      { id: "regular-sugar-kopi-o", label: "Regular sugar", delta: [60, 110] },
    ],
  },
  {
    id: "teh-c-siew-dai",
    name: "Teh C Siew Dai",
    chineseName: "奶茶 C 少糖",
    confidence: "High",
    baseRange: [80, 130],
    macroRange: { protein: [2, 5], carbs: [10, 22], fat: [2, 5] },
    note: "Condensed or evaporated milk and sugar level decide most drink calories.",
    aliases: ["teh c siew dai", "teh c", "milk tea less sugar", "奶茶少糖", "teh siu dai"],
    defaultModifierIds: [],
    modifiers: [
      { id: "iced-teh-c", label: "Iced", delta: [10, 25] },
      { id: "kosong-teh-c", label: "Kosong", delta: [-45, -25] },
      { id: "regular-sugar-teh-c", label: "Regular sugar", delta: [40, 80] },
    ],
  },
  {
    id: "sugarcane-juice",
    name: "Sugarcane Juice",
    chineseName: "甘蔗水",
    confidence: "High",
    baseRange: [150, 260],
    macroRange: { protein: [0, 1], carbs: [36, 64], fat: [0, 1] },
    note: "Refreshing but sugar-heavy. Cup size is the whole estimate.",
    aliases: ["sugarcane juice", "sugar cane", "甘蔗水", "甘蔗汁"],
    defaultModifierIds: [],
    modifiers: [
      { id: "small-sugarcane", label: "Small cup", delta: [-70, -35] },
      { id: "large-sugarcane", label: "Large cup", delta: [70, 130] },
      { id: "less-ice-sugarcane", label: "Less ice", delta: [30, 60] },
    ],
  },
  {
    id: "lime-juice",
    name: "Calamansi / Lime Juice",
    chineseName: "酸柑水",
    confidence: "Medium",
    baseRange: [80, 160],
    macroRange: { protein: [0, 1], carbs: [18, 40], fat: [0, 1] },
    note: "Can be light or sugary depending on syrup. Siew dai matters.",
    aliases: ["calamansi juice", "lime juice", "limau", "酸柑水", "酸梅水"],
    defaultModifierIds: [],
    modifiers: [
      { id: "siew-dai-lime", label: "Less sugar", delta: [-50, -25] },
      { id: "no-sugar-lime", label: "No sugar", delta: [-85, -45] },
      { id: "large-lime", label: "Large cup", delta: [50, 90] },
    ],
  },
  {
    id: "ice-kachang",
    name: "Ice Kachang",
    chineseName: "红豆冰",
    confidence: "Medium",
    baseRange: [260, 430],
    macroRange: { protein: [4, 9], carbs: [58, 92], fat: [2, 8] },
    note: "Dessert range depends on syrup, condensed milk, and toppings.",
    aliases: ["ice kachang", "ais kacang", "红豆冰", "冰 kacang"],
    defaultModifierIds: [],
    modifiers: [
      { id: "less-syrup-kachang", label: "Less syrup", delta: [-80, -40] },
      { id: "condensed-milk-kachang", label: "Condensed milk", delta: [50, 110] },
      { id: "shared-kachang", label: "Shared dessert", delta: [-140, -90] },
    ],
  },
  {
    id: "cendol",
    name: "Cendol",
    chineseName: "煎蕊",
    confidence: "Medium",
    baseRange: [300, 520],
    macroRange: { protein: [4, 9], carbs: [54, 88], fat: [8, 22] },
    note: "Coconut milk and gula melaka make it denser than shaved ice looks.",
    aliases: ["cendol", "chendol", "煎蕊", "珍多冰"],
    defaultModifierIds: [],
    modifiers: [
      { id: "less-gula-cendol", label: "Less gula melaka", delta: [-80, -40] },
      { id: "extra-coconut-cendol", label: "Extra coconut milk", delta: [70, 140] },
      { id: "shared-cendol", label: "Shared dessert", delta: [-170, -110] },
    ],
  }

];
